#![doc = include_str!("../docs/tutorials.md")]
#![doc = include_str!("../docs/how-to.md")]
#![doc = include_str!("../docs/reference.md")]
#![doc = include_str!("../docs/explanation.md")]
#![doc = include_str!("../docs/spool-format.md")]
